#!/bin/sh

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  mkdir -p $HOME/.vim/autoload/
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -e $HOME/.config/nvim/coc-settings.json ]; then
  mkdir -p $HOME/.config/nvim/
fi
cp ../coc-settings.json ~/.vim/
ln -sf $HOME/.vim/coc-settings.json $HOME/.config/nvim/coc-settings.json

vim -u $HOME/.vimrc +PlugInstall +qa -
vim -u $HOME/.vimrc +PlugClean! +qa -
